# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c978a06017258cd08642fe79cce8d9768dd5807919f5d5dbc3290285fad00c7d896463a9f6eeaa61324a3aa0fadfd0a78c65cfa72d27b26c51cd8f66b1c166e9

test:
  secret_key_base: af719728fb87955f0468177578e1c35371958d4bc356e3b3efc05e2b8fdcd93969fe0d4527b4176206ea1f8df48f10dd6aecf485403d0f6f0304bbf307b306ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
